# Generated by Django 6.1 on 2026-08-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_add_rented_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='ownership_type',
            field=models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('rented', 'Rented')], default='owned', max_length=20),
        ),
    ]
