# Generated by Django 6.1 on 2026-08-25

from django.db import migrations, models


def fill_empty_file_data(apps, schema_editor):
    CustomerLocationDocument = apps.get_model(
        "locations",
        "CustomerLocationDocument",
    )

    CustomerLocationDocument.objects.filter(
        file_data__isnull=True
    ).update(
        file_data=b""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_location_credit_hold_status"),
    ]

    operations = [
        # Remove the old FileField that tried to save to /var/task/media
        migrations.RemoveField(
            model_name="customerlocationdocument",
            name="file",
        ),

        # Store the MIME type in the database
        migrations.AddField(
            model_name="customerlocationdocument",
            name="content_type",
            field=models.CharField(
                max_length=150,
                blank=True,
                default="application/octet-stream",
            ),
        ),

        # Add as nullable first so existing rows will not break migration
        migrations.AddField(
            model_name="customerlocationdocument",
            name="file_data",
            field=models.BinaryField(
                null=True,
                blank=True,
            ),
        ),

        # Give existing document rows an empty binary value
        migrations.RunPython(
            fill_empty_file_data,
            migrations.RunPython.noop,
        ),

        # New documents must contain file data
        migrations.AlterField(
            model_name="customerlocationdocument",
            name="file_data",
            field=models.BinaryField(),
        ),
    ]