# Generated by Django 6.1 on 2026-08-14 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('can_access_dashboard', models.BooleanField(default=True)),
                ('can_access_customers', models.BooleanField(default=False)),
                ('can_access_locations', models.BooleanField(default=False)),
                ('can_access_equipment', models.BooleanField(default=False)),
                ('can_access_warranties', models.BooleanField(default=False)),
                ('can_access_licenses', models.BooleanField(default=False)),
                ('can_access_tickets', models.BooleanField(default=False)),
                ('can_access_technicians', models.BooleanField(default=False)),
                ('can_access_billing', models.BooleanField(default=False)),
                ('can_access_reports', models.BooleanField(default=False)),
                ('can_access_users', models.BooleanField(default=False)),
                ('can_access_roles', models.BooleanField(default=False)),
                ('can_access_audit_trail', models.BooleanField(default=False)),
                ('can_access_notifications', models.BooleanField(default=True)),
                ('can_access_settings', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_roles', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='roles.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
