# Generated by Django 6.1 on 2026-08-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Expert Technology Service Management', max_length=150)),
                ('company_name', models.CharField(default='Expert Technology', max_length=150)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('ticket_due_soon_days', models.PositiveIntegerField(default=3, help_text='Number of days before a ticket due date to send a notification.')),
                ('warranty_expiry_warning_days', models.PositiveIntegerField(default=30, help_text='Number of days before warranty expiration to send a notification.')),
                ('license_expiry_warning_days', models.PositiveIntegerField(default=30, help_text='Number of days before license expiration to send a notification.')),
                ('timezone', models.CharField(choices=[('Asia/Manila', 'Asia/Manila'), ('UTC', 'UTC'), ('America/New_York', 'America/New_York'), ('America/Chicago', 'America/Chicago'), ('America/Denver', 'America/Denver'), ('America/Los_Angeles', 'America/Los_Angeles')], default='Asia/Manila', max_length=100)),
                ('date_format', models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='MM/DD/YYYY', max_length=20)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60, help_text='Automatic logout time in minutes.')),
                ('require_strong_password', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
